// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jxxlduhxfsxxvljqsqmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4eGxkdWh4ZnN4eHZsanFzcW13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MjcyNjIsImV4cCI6MjA2NTAwMzI2Mn0.nECZiggRXYN5uTiGTwd4fUx8vbLPXS8F_xfMYx00wLA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);